apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "option-trade-executor-app"
  namespace: "default"
  labels:
    app: "option-trade-executor-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "option-trade-executor-app"
  template:
    metadata:
      labels:
        app: "option-trade-executor-app"
    spec:
      containers:
      - name: "optiontradeexecutorservice"
        image: "gcr.io/fifth-curve-382514/optiontradeexecutorservice:latest"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/pubsub-key.json
        volumeMounts:
          - name: cloud-pubsub-key
            mountPath: /secrets/
#      - name: cloud-sql-proxy
#        image: gcr.io/cloudsql-docker/gce-proxy:1.28.0 # make sure the use the latest version
#        command:
#          - "/cloud_sql_proxy"
#          - "-log_debug_stdout"
#          - "-instances=fifth-curve-382514:asia-south2:options-trading=tcp:127.0.0.1:3306"
#          - "-credential_file=/secrets/key.json"
#        securityContext:
#          runAsNonRoot: true
#        volumeMounts:
#          - name: cloud-sql-key
#            mountPath: /secrets/
#            readOnly: true

        resources:
          requests:
            # The proxy's memory use scales linearly with the number of active
            # connections. Fewer open connections will use less memory. Adjust
            # this value based on your application's requirements.
            memory: "256M"
            # The proxy's CPU use scales linearly with the amount of IO between
            # the database and the application. Adjust this value based on your
            # application's requirements.
            cpu:    "250m"
      volumes:
#        - name: cloud-sql-key
#          secret:
#            secretName: service-account-credentials
        - name: cloud-pubsub-key
          secret:
            secretName: pubsub-key
        # [END cloud_sql_proxy_k8s_volume_secret]
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "option-trade-executor-app-hpa-oxla"
  namespace: "default"
  labels:
    app: "option-trade-executor-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "option-trade-executor-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
