core.service.OptionTradeExecutorService.class=executorservice.OptionTradeExecutorService
OptionTradeExecutorService-PROTO_STRING-DOMAIN_OBJECT=transformers.OptionTradeRequestTransformer
OptionTradeExecutorService-DOMAIN_OBJECT-PROTO_BINARY=transformers.QueryResponseTransformer