option.trading.optiondb.connectionString=org.postgresql.Driver,jdbc:postgresql://localhost:3306/options-trading-db,postgres,admin
option.trading.optiondb.key=optionDB
option.trading.connection.pool.size=5