service.pod.name.prefix=option.trading
option.trading.project.id=fifth-curve-382514
option.trading.subscription.id=options-data-topic-sub

core.grpc.ComputeServicePod.port.1=20700
option.trading.user.api.key.1=n290rmp3zhzbkxtt
option.trading.user.id.1=CAV264
option.trading.user.name.1= Gaurav
option.trading.user.api.secret.1=lnno10oz2det9bx60xas6i1wvv6x1kng
option.trading.user.public.token.1=
option.trading.user.access.token.1=VfBxzfzzoy6K7rTPnh164xkux7uRzYGG

option.trading.user.api.key.2=penkol14uxnyj40z
option.trading.user.id.2=HGU653
option.trading.user.api.secret.2=nmi0o9oad3chot5qxxo7gm5yi718qxgu
option.trading.user.public.token.2=zoSKvdEgpolbeSWBz5CbUgjNbnMGw81s
option.trading.user.access.token.2=Uec3Hcf0jGDczC0Z291itOTiLRsedqQZ

option.trading.user.api.key.3=zyppp731lbi6co2g
option.trading.user.id.3=TOC072
option.trading.user.name.3= Mohit
option.trading.user.api.secret.3=2ibr5lqcywqzyzonsqgomvc949oshq64
option.trading.user.public.token.3=0g0mhoDmy7C6frUrtJNbEWcOdLRB26L3
option.trading.user.access.token.3=pGWaziwzpI39Ej4HdO9Fh61n5vl8l53Y

option.trading.user.client.mapping=TOC072:3
option.trading.trade.executor.count=5
buffer.type=QUEUE
option.trading.default.stop.loss=2000
core.grpc.client.host.port.DataMaintenancePod=writer-server:80
core.grpc.client.host.port.QueryServicePod=query-server:80
#core.grpc.client.host.port.QueryServicePod=localhost:20400
#core.grpc.client.host.port.DataMaintenancePod=localhost:21400
